# Generated by Django 5.2.5 on 2025-08-08 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_cp", models.FloatField(blank=True, null=True)),
                ("total_bags", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cp",
                    models.FloatField(
                        blank=True, help_text="Crude Protein %", null=True
                    ),
                ),
                ("fat", models.FloatField(blank=True, null=True)),
                ("tvbn", models.FloatField(blank=True, null=True)),
                ("ash", models.FloatField(blank=True, null=True)),
                ("ffa", models.FloatField(blank=True, null=True)),
                ("bags_available", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductMixResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bags_used", models.FloatField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mix",
                        to="mixengine.productorder",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mixengine.sample",
                    ),
                ),
            ],
        ),
    ]
