# Generated by Django 5.2.5 on 2025-08-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mixengine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="fiber",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="lot_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="moisture",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="production_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="remaining_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="used_quantity",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
