# Generated by Django 5.2.5 on 2025-12-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mixengine",
            "0002_sample_fiber_sample_last_updated_sample_lot_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="final_values",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productorder",
            name="targets",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productorder",
            name="variances",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
